### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by max-poltora** [12rambau/pygadm#22] opened 2023-06-05 07:20 UTC
Hi,

I am trying to execute the code, that worked a few days back but fails today.

```python
import pygadm

country_name = 'Kenya'
adm_level = 1
gdf = pygadm.get_items(name=country_name, content_level=adm_level)
```
Output are different:
> DriverError: CURL error: Failed to connect to geodata.ucdavis.edu port 443 after 21037 ms: Couldn't connect to server

And another one:
> DriverError: CURL error: SSL/TLS connection timeout

**Comment by 12rambau** [comment] 2023-06-05 11:29
It has already happen last year, I just checked myself with this url: https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_ECU_0.json, it effectively never loads. The problem is coming from GADM servers, so unfortunately nothing I can do from here. I'll close the issue once the servers are back online and add a more meaningful error message if this is raised again.

**Comment by max-poltora** [comment] 2023-06-05 12:02
@12rambau, ok! Thanks for the respond!

**Comment by 12rambau** [comment] 2023-06-08 06:48
server is back online

**Closed by 12rambau** 2023-06-08 06:48 UTC
